Code style changes

diff --git a/src/install/ykfde b/src/install/ykfde
--- a/src/install/ykfde
+++ b/src/install/ykfde
@@ -1,6 +1,14 @@
 #!/usr/bin/env bash
 
+YKFDE_CONFIG_FILE="/etc/ykfde.conf"
+YKFDE_NFC=""
+
 build() {
+  . "$YKFDE_CONFIG_FILE" || {
+    ykfde_err 001 "Failed to read the YKFDE configuration file '$YKFDE_CONFIG_FILE'"
+    exit 1
+  }
+
   local mod
 
   add_module "dm-crypt"
@@ -13,13 +21,17 @@ build() {
     add_all_modules "/crypto/"
   fi
 
-  # serial drivers for nfc
-  add_all_modules "/drivers/tty/serial/"
-  add_all_modules "/drivers/usb/serial/"
+  if [ "$YKFDE_NFC" ]; then
+    # serial drivers for nfc
+    add_all_modules "/drivers/tty/serial/"
+    add_all_modules "/drivers/usb/serial/"
 
-  # nfc challenge response
-  add_file "/etc/nfc/libnfc.conf"
-  add_binary "/usr/lib/initcpio/ykchalresp-nfc" "/usr/bin/ykchalresp-nfc"
+    # nfc challenge response
+    if [ -f "/etc/nfc/libnfc.conf" ]; then
+      add_file "/etc/nfc/libnfc.conf"
+    fi
+    add_binary "/usr/lib/initcpio/ykchalresp-nfc" "/usr/bin/ykchalresp-nfc"
+  fi
 
   add_binary "cryptsetup"
   add_binary "dmsetup"
@@ -41,6 +53,17 @@ build() {
   add_file "/usr/lib/ykfde-suspend/initramfs-suspend" "/ykfde-suspend" 755
 
   add_runscript
+}
+
+ykfde_err() {
+  local _rc
+  _rc="$?"
+  local code
+  code="$1"
+  local msg
+  msg="$2"
+  [ "$msg" ] && msg="ERROR $code [rc=$_rc]: $msg" || msg="ERROR $code [rc=$_rc]"
+  printf '\n%s\n\n' "$msg" #exit 1;
 }
 
 help() {
