Grammar Patch (#22)
* Optional Grammar fixes.

There were a few phrasing errors in the Echo.

* Grammar Patch

* Merged Grammar Patches

* Missed grammar fixes

* Update initramfs-suspend

* Update initramfs-suspend

* Grammar fixes

* Merge request fixes.

* Merge request fixes

* Merge request fixes

* Merge request fixes

* Re-add password prompt line

diff --git a/src/hooks/ykfde b/src/hooks/ykfde
--- a/src/hooks/ykfde
+++ b/src/hooks/ykfde
@@ -36,14 +36,14 @@ ykfde_challenge_response() {
         if [ "$_yubikey_timeout" -eq -1 ] || [ $_usedtime -le "$_yubikey_timeout" ]; then
             sleep 0.5
         else
-            echo "    TIMEOUT - Giving up with Challenge-Response!"
+            echo "    Timeout - Challenge-Response aborted."
             return 1 # timeout
         fi
     done
 
     if [ "$YKFDE_CHALLENGE_PASSWORD_NEEDED" = "1" ]; then
         local _pw="";
-        echo " > Please provide password which will be used as challenge."
+        echo " > Please provide the challenge password."
         while [ -z "$_pw" ]; do
             printf "   Enter password: "; if [ "$DBG" ]; then read -r _pw; else read -r -s _pw; fi
             _pw=$(printf %s "$_pw" | sha256sum | awk '{print $1}')
@@ -52,18 +52,18 @@ ykfde_challenge_response() {
         YKFDE_CHALLENGE="$_pw"
     fi
 
-    echo "   YubiKey detected! - Don't forget to press its button if necessary..."
-    [ "$DBG" ] && echo "   Running NOW: ykchalresp -$YKFDE_CHALLENGE_SLOT \"$YKFDE_CHALLENGE\"..."
+    echo "   Remember to touch the device if necessary."
+    [ "$DBG" ] && echo "   Running: ykchalresp -$YKFDE_CHALLENGE_SLOT \"$YKFDE_CHALLENGE\"..."
     _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null| tr -d '\n')"
     if [ -z "$_passphrase" ]; then
-      printf "\n   NO response from YubiKey!? - We try again! (so press the button now?!)...\n"
+      printf "\n   Yubikey did not provide a response - Initializing second attempt, touch the device if necessary.\n"
       _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null| tr -d '\n')"
     fi
     if [ -z "$_passphrase" ]; then
-      printf "\n   NO response from YubiKey!? - Last trial of ykchalresp...\n"
+      printf "\n   Yubikey did not provide a response - Initializing final attempt, touch the device if necessary.\n"
       _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null| tr -d '\n')"
     fi
-    [ "$DBG" ] && printf "\n   Got as response: '$_passphrase'\n"
+    [ "$DBG" ] && printf "\n   Received response: '$_passphrase'\n"
 
     if [ -n "$_passphrase" ] && [ "$YKFDE_CHALLENGE_PASSWORD_NEEDED" = "1" ]; then
       _passphrase="$_pw$_passphrase"
@@ -82,28 +82,28 @@ ykfde_do_it() {
 
     if [ -z "$_passphrase" ]; then
         if [ -n "$YKFDE_CHALLENGE" ]; then
-          printf " > Failed to do challenge-response.\n   Falling back to manual passphrase entering to unlock the disk.\n"
-          [ "$trial_nr" -le "$YKFDE_CRYPTSETUP_TRIALS" ] && echo "   Just press ENTER to skip and to try Challenge-Response again."
+          printf " > Challenge-response failed.\n   Falling back to manual passphrase.\n"
+          [ "$trial_nr" -le "$YKFDE_CRYPTSETUP_TRIALS" ] && echo "   Press ENTER to skip and retry Challenge-Response."
         else
-          echo " > We need the passphrase to unlock the disk."
+          echo " > Passphrase needed to unlock disk."
         fi
 
         printf "   Enter passphrase: "; if [ "$DBG" ]; then read -r _passphrase; else read -r -s _passphrase; fi
         [ "$DBG" ] || echo # if /NOT/ DBG, we need to output \n here.
     fi
 
-    [ -e "$YKFDE_LUKS_DEV" ] || { ykfde_err 003 "ykfde can't find LUKS device '$YKFDE_LUKS_DEV'.\nPlease check YKFDE_DISK_UUID ($YKFDE_DISK_UUID) and/or YKFDE_LUKS_DEV variable(s) in '$YKFDE_CONFIG_FILE'."; return 1; }
+    [ -e "$YKFDE_LUKS_DEV" ] || { ykfde_err 003 "YKFDE cannot find LUKS device '$YKFDE_LUKS_DEV'.\nPlease check YKFDE_DISK_UUID ($YKFDE_DISK_UUID) and/or YKFDE_LUKS_DEV variable(s) in '$YKFDE_CONFIG_FILE'."; return 1; }
 
-    [ "$DBG" ] && echo " > Using '$_passphrase' with cryptsetup!"
+    [ "$DBG" ] && echo " > Passing '$_passphrase' to cryptsetup!"
     [ "$DBG" ] && echo " > Decrypting (cryptsetup luksOpen \"$YKFDE_LUKS_DEV\" \"$YKFDE_LUKS_NAME\")..." || echo " > Decrypting (cryptsetup luksOpen)..."
 
     _tmp="$(printf %s "$_passphrase"| cryptsetup luksOpen "$YKFDE_LUKS_DEV" "$YKFDE_LUKS_NAME" 2>&1)";
     _rc=$?;
 
     if [ $_rc -eq 0 ]; then
-        echo "   SUCCESS :)";
+        echo "   Decryption was succesful.";
         if [ -n "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP" ] && [ "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP" -gt 0 ]; then
-          [ "$DBG" ] && echo " > Sleeping $YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP bevore moving on..."
+          [ "$DBG" ] && echo " > Making $YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP sleep."
           sleep "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP"
         fi;
     else
@@ -119,10 +119,10 @@ run_hook() {
 
     [ "$DBG" ] && echo "$0:"
 
-    [ "$DBG" ] && echo " > Reading YKFDE_CONFIG_FILE..."
-    . "$YKFDE_CONFIG_FILE" || { ykfde_err 001 "Failed reading YKFDE_CONFIG_FILE '$YKFDE_CONFIG_FILE'"; return 1; }
+    [ "$DBG" ] && echo " > Reading YKFDE configuration file."
+    . "$YKFDE_CONFIG_FILE" || { ykfde_err 001 "Failed to read the YKFDE configuration file '$YKFDE_CONFIG_FILE'"; return 1; }
 
-    [ -z "$YKFDE_DISK_UUID" ] || [ -z "$YKFDE_LUKS_NAME" ] && { ykfde_err 002 "'$YKFDE_CONFIG_FILE' must provide YKFDE_DISK_UUID /and/ YKFDE_LUKS_NAME."; return 1; }
+    [ -z "$YKFDE_DISK_UUID" ] || [ -z "$YKFDE_LUKS_NAME" ] && { ykfde_err 002 "'$YKFDE_CONFIG_FILE' Please provide YKFDE_DISK_UUID /and/ YKFDE_LUKS_NAME."; return 1; }
 
     # set default values:
     [ -z "$YKFDE_LUKS_DEV" ] && YKFDE_LUKS_DEV="/dev/disk/by-uuid/$YKFDE_DISK_UUID"
@@ -130,24 +130,24 @@ run_hook() {
     [ -z "$YKFDE_CRYPTSETUP_TRIALS" ] && YKFDE_CRYPTSETUP_TRIALS="$DEFAULT_CRYPTSETUP_TRIALS"
 
     # sanity checks:
-    [ $YKFDE_CRYPTSETUP_TRIALS -gt 0 ] || { ykfde_err 006 "YKFDE_CRYPTSETUP_TRIALS needs to be a number > 0."; return 1; }
+    [ $YKFDE_CRYPTSETUP_TRIALS -gt 0 ] || { ykfde_err 006 "YKFDE_CRYPTSETUP_TRIALS needs to be higher than 0."; return 1; }
 
-    [ "$DBG" ] && echo " > udevadm settle..."
-    udevadm settle || { ykfde_err 004 "Failed to 'udevadm settle'"; return 1; }
+    [ "$DBG" ] && echo " > Settling udevadm."
+    udevadm settle || { ykfde_err 004 "Failed to settle udevadm."; return 1; }
 
-    [ "$DBG" ] && echo " > modprobe -a -q dm-crypt..."
-    tmp="$(modprobe -a dm-crypt 2>&1)" || { ykfde_err 005 "FAILED to 'modprobe -a -q dm-crypt':\n$tmp"; return 1; }
+    [ "$DBG" ] && echo " > modprobing dm-crypt"
+    tmp="$(modprobe -a dm-crypt 2>&1)" || { ykfde_err 005 "Failed executing 'modprobe -a -q dm-crypt':\n$tmp"; return 1; }
 
     local trial_nr=1;
     local what="$YKFDE_DISK_UUID"; [ -n "$YKFDE_LUKS_NAME" ] && s=" $YKFDE_LUKS_NAME";
     while [ $trial_nr -le $YKFDE_CRYPTSETUP_TRIALS ]; do
-      printf "\nTRIAL #$trial_nr/$YKFDE_CRYPTSETUP_TRIALS: cryptsetup of $what\n"
+      printf "\nAttempt #$trial_nr/$YKFDE_CRYPTSETUP_TRIALS: cryptsetup of $what\n"
       ykfde_do_it && return 0;
       trial_nr=$(( trial_nr + 1 ));
     done
 
     # if we get here, we did NOT succeed:
-    ykfde_err 000 "$0 FAILED !"
+    ykfde_err 000 "$0 Failed!"
     return 1;
 }
 
