Code beautyfication
Done with shfmt tool (https://github.com/mvdan/sh). No functional changes

diff --git a/src/hooks/ykfde b/src/hooks/ykfde
--- a/src/hooks/ykfde
+++ b/src/hooks/ykfde
@@ -2,175 +2,186 @@
 
 YKFDE_CONFIG_FILE="/etc/ykfde.conf"
 
-DEFAULT_CRYPTSETUP_TRIALS=5;                   # defaults number of times to try 'do_it()' -- so: assemble passphrase and run 'cryptsetup luksOpen'
-DEFAULT_CHALLENGE_YUBIKEY_INSERT_TIMEOUT=30;   # default value for YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT. -1 = unlimited
+DEFAULT_CRYPTSETUP_TRIALS=5                 # defaults number of times to try 'do_it()' -- so: assemble passphrase and run 'cryptsetup luksOpen'
+DEFAULT_CHALLENGE_YUBIKEY_INSERT_TIMEOUT=30 # default value for YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT. -1 = unlimited
 
-
-ykfde_err() { local rc="$?"; local code="$1"; local msg="$2";
-  [ -n "$msg" ] && msg="ERROR $code [rc=$rc]: $msg" || msg="ERROR $code [rc=$rc]";
-  printf '\n%s\n\n' "$msg"; #exit 1;
+ykfde_err() {
+  local rc="$?"
+  local code="$1"
+  local msg="$2"
+  [ -n "$msg" ] && msg="ERROR $code [rc=$rc]: $msg" || msg="ERROR $code [rc=$rc]"
+  printf '\n%s\n\n' "$msg" #exit 1;
 }
 
 ykfde_challenge_response() {
-    local _yubikey_timeout="$YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT"
-    local _yubikey_timeout_str=""
-    local _yubikey_detected=""
-    local _starttime=""               # to determine if a timeout occured
-    local _endtime=""
-    local _usedtime=""
-    local _tmp="";
-    local _rc="";
+  local _yubikey_timeout="$YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT"
+  local _yubikey_timeout_str=""
+  local _yubikey_detected=""
+  local _starttime="" # to determine if a timeout occured
+  local _endtime=""
+  local _usedtime=""
+  local _tmp=""
+  local _rc=""
 
-    [ "$YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT" -gt 0 ] && _yubikey_timeout_str="$YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT seconds"
+  [ "$YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT" -gt 0 ] && _yubikey_timeout_str="$YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT seconds"
 
-    _starttime=$(date +%s)
-    echo " > Waiting $_yubikey_timeout_str for YubiKey..."
+  _starttime=$(date +%s)
+  echo " > Waiting $_yubikey_timeout_str for YubiKey..."
 
-    while [ -z "$_yubikey_detected" ]; do
-        _endtime=$(date +%s)
-        _usedtime=$(( _endtime - _starttime ))
-        [ "$DBG" ] && printf %s "   (used time:$_usedtime, timeout:$_yubikey_timeout) ykinfo -$YKFDE_CHALLENGE_SLOT \"$YKFDE_CHALLENGE\": "
-        _tmp="$(ykinfo -"$YKFDE_CHALLENGE_SLOT" 2>&1)"; _rc=$?;
-        [ "$DBG" ] && echo "[$_rc] '$_tmp'"
-        [ $_rc -eq 0 ] && _yubikey_detected=1;
-        if [ "$_yubikey_timeout" -eq -1 ] || [ $_usedtime -le "$_yubikey_timeout" ]; then
-            sleep 0.5
-        else
-            echo "    Timeout - Challenge-Response aborted."
-            return 1 # timeout
-        fi
+  while [ -z "$_yubikey_detected" ]; do
+    _endtime=$(date +%s)
+    _usedtime=$((_endtime - _starttime))
+    [ "$DBG" ] && printf %s "   (used time:$_usedtime, timeout:$_yubikey_timeout) ykinfo -$YKFDE_CHALLENGE_SLOT \"$YKFDE_CHALLENGE\": "
+    _tmp="$(ykinfo -"$YKFDE_CHALLENGE_SLOT" 2>&1)"
+    _rc=$?
+    [ "$DBG" ] && echo "[$_rc] '$_tmp'"
+    [ $_rc -eq 0 ] && _yubikey_detected=1
+    if [ "$_yubikey_timeout" -eq -1 ] || [ $_usedtime -le "$_yubikey_timeout" ]; then
+      sleep 0.5
+    else
+      echo "    Timeout - Challenge-Response aborted."
+      return 1 # timeout
+    fi
+  done
+
+  if [ -n "$YKFDE_CHALLENGE_PASSWORD_NEEDED" ]; then
+    local _pw=""
+    echo " > Please provide the challenge password."
+    while [ -z "$_pw" ]; do
+      printf "   Enter password: "
+      if [ "$DBG" ]; then read -r _pw; else read -r -s _pw; fi
+      _pw=$(printf %s "$_pw" | sha256sum | awk '{print $1}')
     done
+    [ "$DBG" ] || echo # if /NOT/ DBG, we need to output \n here.
+    YKFDE_CHALLENGE="$_pw"
+  fi
 
-    if [ -n "$YKFDE_CHALLENGE_PASSWORD_NEEDED" ]; then
-        local _pw="";
-        echo " > Please provide the challenge password."
-        while [ -z "$_pw" ]; do
-            printf "   Enter password: "; if [ "$DBG" ]; then read -r _pw; else read -r -s _pw; fi
-            _pw=$(printf %s "$_pw" | sha256sum | awk '{print $1}')
-        done
-        [ "$DBG" ] || echo # if /NOT/ DBG, we need to output \n here.
-        YKFDE_CHALLENGE="$_pw"
-    fi
+  echo "   Remember to touch the device if necessary."
+  [ "$DBG" ] && echo "   Running: ykchalresp -$YKFDE_CHALLENGE_SLOT \"$YKFDE_CHALLENGE\"..."
+  _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null | tr -d '\n')"
+  if [ -z "$_passphrase" ]; then
+    printf "\\n   YubiKey did not provide a response - Initializing second attempt, touch the device if necessary.\\n"
+    _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null | tr -d '\n')"
+  fi
+  if [ -z "$_passphrase" ]; then
+    printf "\\n   YubiKey did not provide a response - Initializing final attempt, touch the device if necessary.\\n"
+    _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null | tr -d '\n')"
+  fi
+  [ "$DBG" ] && printf '%s\n' "   Received response: '$_passphrase'"
 
-    echo "   Remember to touch the device if necessary."
-    [ "$DBG" ] && echo "   Running: ykchalresp -$YKFDE_CHALLENGE_SLOT \"$YKFDE_CHALLENGE\"..."
-    _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null| tr -d '\n')"
-    if [ -z "$_passphrase" ]; then
-      printf "\\n   YubiKey did not provide a response - Initializing second attempt, touch the device if necessary.\\n"
-      _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null| tr -d '\n')"
-    fi
-    if [ -z "$_passphrase" ]; then
-      printf "\\n   YubiKey did not provide a response - Initializing final attempt, touch the device if necessary.\\n"
-      _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null| tr -d '\n')"
-    fi
-    [ "$DBG" ] && printf '%s\n' "   Received response: '$_passphrase'"
-
-    if [ -n "$_passphrase" ] && [ -n "$YKFDE_CHALLENGE_PASSWORD_NEEDED" ]; then
-      _passphrase="$_pw$_passphrase"
-    fi
+  if [ -n "$_passphrase" ] && [ -n "$YKFDE_CHALLENGE_PASSWORD_NEEDED" ]; then
+    _passphrase="$_pw$_passphrase"
+  fi
 }
-
 
 # assemble passphrase and run 'cryptsetup luksOpen'
 ykfde_do_it() {
-    local _passphrase=""                     # key used to 'cryptsetup luksOpen'
-    local _tmp="";
-    local _rc="";
+  local _passphrase="" # key used to 'cryptsetup luksOpen'
+  local _tmp=""
+  local _rc=""
 
-    # if we have a challenge
-    [ -n "$YKFDE_CHALLENGE" ] && ykfde_challenge_response
+  # if we have a challenge
+  [ -n "$YKFDE_CHALLENGE" ] && ykfde_challenge_response
 
-    if [ -z "$_passphrase" ]; then
-        if [ -n "$YKFDE_CHALLENGE" ]; then
-          printf " > Challenge-response failed.\\n   Falling back to manual passphrase.\\n"
-          [ "$trial_nr" -le "$YKFDE_CRYPTSETUP_TRIALS" ] && echo "   Press ENTER to skip and retry Challenge-Response."
-        else
-          echo " > Passphrase needed to unlock disk."
-        fi
-
-        printf "   Enter passphrase: "; if [ "$DBG" ]; then read -r _passphrase; else read -r -s _passphrase; fi
-        [ "$DBG" ] || echo # if /NOT/ DBG, we need to output \n here.
-    fi
-
-    [ -e "$YKFDE_LUKS_DEV" ] || { ykfde_err 003 "YKFDE cannot find LUKS device '$YKFDE_LUKS_DEV'.\\nPlease check YKFDE_DISK_UUID ($YKFDE_DISK_UUID) and/or YKFDE_LUKS_DEV variable(s) in '$YKFDE_CONFIG_FILE'."; return 1; }
-
-    [ "$DBG" ] && echo " > Passing '$_passphrase' to cryptsetup!"
-    if [ -n "$RESUME" ]; then
-        [ "$DBG" ] && echo " > Decrypting (cryptsetup luksResume \"$cryptname\"..." || echo " > Decrypting (cryptsetup luksResume)..."
-        _tmp="$(printf %s "$_passphrase"| cryptsetup luksResume "${cryptname}" 2>&1;)";
+  if [ -z "$_passphrase" ]; then
+    if [ -n "$YKFDE_CHALLENGE" ]; then
+      printf " > Challenge-response failed.\\n   Falling back to manual passphrase.\\n"
+      [ "$trial_nr" -le "$YKFDE_CRYPTSETUP_TRIALS" ] && echo "   Press ENTER to skip and retry Challenge-Response."
     else
-        [ "$DBG" ] && echo " > Decrypting (cryptsetup luksOpen \"$YKFDE_LUKS_DEV\" \"$YKFDE_LUKS_NAME\")..." || echo " > Decrypting (cryptsetup luksOpen)..."
-        _tmp="$(printf %s "$_passphrase"| cryptsetup luksOpen "$YKFDE_LUKS_DEV" "$YKFDE_LUKS_NAME" "$YKFDE_LUKS_OPTIONS" 2>&1)";
-    fi
-    _rc=$?;
-
-    if [ $_rc -eq 0 ]; then
-        echo "   Decryption was succesful.";
-        if [ -n "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP" ] && [ "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP" -gt 0 ]; then
-          [ "$DBG" ] && echo " > Making $YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP sleep."
-          sleep "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP"
-        fi;
-    else
-        echo "   FAILED! [$_rc] $_tmp";
+      echo " > Passphrase needed to unlock disk."
     fi
 
-    return $_rc;
+    printf "   Enter passphrase: "
+    if [ "$DBG" ]; then read -r _passphrase; else read -r -s _passphrase; fi
+    [ "$DBG" ] || echo # if /NOT/ DBG, we need to output \n here.
+  fi
+
+  [ -e "$YKFDE_LUKS_DEV" ] || {
+    ykfde_err 003 "YKFDE cannot find LUKS device '$YKFDE_LUKS_DEV'.\\nPlease check YKFDE_DISK_UUID ($YKFDE_DISK_UUID) and/or YKFDE_LUKS_DEV variable(s) in '$YKFDE_CONFIG_FILE'."
+    return 1
+  }
+
+  [ "$DBG" ] && echo " > Passing '$_passphrase' to cryptsetup!"
+  if [ -n "$RESUME" ]; then
+    [ "$DBG" ] && echo " > Decrypting (cryptsetup luksResume \"$cryptname\"..." || echo " > Decrypting (cryptsetup luksResume)..."
+    _tmp="$(printf %s "$_passphrase" | cryptsetup luksResume "${cryptname}" 2>&1)"
+  else
+    [ "$DBG" ] && echo " > Decrypting (cryptsetup luksOpen \"$YKFDE_LUKS_DEV\" \"$YKFDE_LUKS_NAME\")..." || echo " > Decrypting (cryptsetup luksOpen)..."
+    _tmp="$(printf %s "$_passphrase" | cryptsetup luksOpen "$YKFDE_LUKS_DEV" "$YKFDE_LUKS_NAME" "$YKFDE_LUKS_OPTIONS" 2>&1)"
+  fi
+  _rc=$?
+
+  if [ $_rc -eq 0 ]; then
+    echo "   Decryption was succesful."
+    if [ -n "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP" ] && [ "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP" -gt 0 ]; then
+      [ "$DBG" ] && echo " > Making $YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP sleep."
+      sleep "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP"
+    fi
+  else
+    echo "   FAILED! [$_rc] $_tmp"
+  fi
+
+  return $_rc
 }
-
 
 run_hook() {
-    local _tmp=""
-    local cryptargs cryptopt cryptoptions
+  local _tmp=""
+  local cryptargs cryptopt cryptoptions
 
-    [ "$DBG" ] && echo "$0:"
+  [ "$DBG" ] && echo "$0:"
 
-    [ "$DBG" ] && echo " > Reading YKFDE configuration file."
-    . "$YKFDE_CONFIG_FILE" || { ykfde_err 001 "Failed to read the YKFDE configuration file '$YKFDE_CONFIG_FILE'"; return 1; }
+  [ "$DBG" ] && echo " > Reading YKFDE configuration file."
+  . "$YKFDE_CONFIG_FILE" || {
+    ykfde_err 001 "Failed to read the YKFDE configuration file '$YKFDE_CONFIG_FILE'"
+    return 1
+  }
 
-    # no settings in config, try to pull it from kernel cmdline (analog to encrypt hook)
-    if [ -z "$YKFDE_DISK_UUID" ] || [ -z "$YKFDE_LUKS_NAME" ] ; then
-        if [ -n "${cryptdevice}" ] ; then
-            IFS=: read -r YKFDE_LUKS_DEV YKFDE_LUKS_NAME cryptoptions <<EOF
+  # no settings in config, try to pull it from kernel cmdline (analog to encrypt hook)
+  if [ -z "$YKFDE_DISK_UUID" ] || [ -z "$YKFDE_LUKS_NAME" ]; then
+    if [ -n "${cryptdevice}" ]; then
+      IFS=: read -r YKFDE_LUKS_DEV YKFDE_LUKS_NAME cryptoptions <<EOF
 $cryptdevice
 EOF
-            for cryptopt in $(echo "$cryptoptions" | tr , ' '); do
-                case ${cryptopt} in
-                    allow-discards)
-                        cryptargs="${cryptargs} --allow-discards"
-                        ;;
-                    *)
-                        ykfde_err 001 "Encryption option '${cryptopt}' not known, ignoring." 
-                        ;;
-                esac
-            done
-            YKFDE_LUKS_OPTIONS=$cryptargs
-            YKFDE_LUKS_DEV=$(resolve_device "${YKFDE_LUKS_DEV}")
-        else
-            ykfde_err 002 "'$YKFDE_CONFIG_FILE' Please provide YKFDE_DISK_UUID /and/ YKFDE_LUKS_NAME or set cryptdevice kernel parameter."
-            return 1
-        fi
+      for cryptopt in $(echo "$cryptoptions" | tr , ' '); do
+        case ${cryptopt} in
+          allow-discards)
+            cryptargs="${cryptargs} --allow-discards"
+            ;;
+          *)
+            ykfde_err 001 "Encryption option '${cryptopt}' not known, ignoring."
+            ;;
+        esac
+      done
+      YKFDE_LUKS_OPTIONS=$cryptargs
+      YKFDE_LUKS_DEV=$(resolve_device "${YKFDE_LUKS_DEV}")
+    else
+      ykfde_err 002 "'$YKFDE_CONFIG_FILE' Please provide YKFDE_DISK_UUID /and/ YKFDE_LUKS_NAME or set cryptdevice kernel parameter."
+      return 1
     fi
+  fi
 
-    # set default values:
-    [ -z "$YKFDE_LUKS_DEV" ] && YKFDE_LUKS_DEV="/dev/disk/by-uuid/$YKFDE_DISK_UUID"
-    [ -z "$YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT" ] && YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT="$DEFAULT_CHALLENGE_YUBIKEY_INSERT_TIMEOUT"
-    [ -z "$YKFDE_CRYPTSETUP_TRIALS" ] && YKFDE_CRYPTSETUP_TRIALS="$DEFAULT_CRYPTSETUP_TRIALS"
+  # set default values:
+  [ -z "$YKFDE_LUKS_DEV" ] && YKFDE_LUKS_DEV="/dev/disk/by-uuid/$YKFDE_DISK_UUID"
+  [ -z "$YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT" ] && YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT="$DEFAULT_CHALLENGE_YUBIKEY_INSERT_TIMEOUT"
+  [ -z "$YKFDE_CRYPTSETUP_TRIALS" ] && YKFDE_CRYPTSETUP_TRIALS="$DEFAULT_CRYPTSETUP_TRIALS"
 
-    # sanity checks:
-    [ $YKFDE_CRYPTSETUP_TRIALS -gt 0 ] || { ykfde_err 004 "YKFDE_CRYPTSETUP_TRIALS needs to be higher than 0."; return 1; }
+  # sanity checks:
+  [ $YKFDE_CRYPTSETUP_TRIALS -gt 0 ] || {
+    ykfde_err 004 "YKFDE_CRYPTSETUP_TRIALS needs to be higher than 0."
+    return 1
+  }
 
-    [ "$DBG" ] && echo " > modprobing dm-crypt"
-    _tmp="$(modprobe -a -q dm-crypt >/dev/null 2>&1)"
+  [ "$DBG" ] && echo " > modprobing dm-crypt"
+  _tmp="$(modprobe -a -q dm-crypt >/dev/null 2>&1)"
 
-    local trial_nr=1;
-    while [ $trial_nr -le $YKFDE_CRYPTSETUP_TRIALS ]; do
-      printf '%s\n' "Attempt #$trial_nr/$YKFDE_CRYPTSETUP_TRIALS: cryptsetup of $YKFDE_LUKS_DEV"
-      ykfde_do_it && return 0;
-      trial_nr=$(( trial_nr + 1 ));
-    done
+  local trial_nr=1
+  while [ $trial_nr -le $YKFDE_CRYPTSETUP_TRIALS ]; do
+    printf '%s\n' "Attempt #$trial_nr/$YKFDE_CRYPTSETUP_TRIALS: cryptsetup of $YKFDE_LUKS_DEV"
+    ykfde_do_it && return 0
+    trial_nr=$((trial_nr + 1))
+  done
 
-    # if we get here, we did NOT succeed:
-    ykfde_err 000 "$0 Failed!"
-    return 1;
+  # if we get here, we did NOT succeed:
+  ykfde_err 000 "$0 Failed!"
+  return 1
 }
-
diff --git a/src/ykfde-enroll b/src/ykfde-enroll
--- a/src/ykfde-enroll
+++ b/src/ykfde-enroll
@@ -3,104 +3,109 @@
 set -e
 . /etc/ykfde.conf
 
+while getopts ":s:d:hcv" opt; do
+  case $opt in
+    s)
+      KEY_SLOT="$OPTARG"
+      printf '%s\n' "INFO: Setting LUKS key slot to \"$OPTARG\"."
+      ;;
+    d)
+      YKFDE_LUKS_DEV="$OPTARG"
+      printf '%s\n' "INFO: Setting disk to \"$OPTARG\"."
+      ;;
+    c)
+      CLEAR_KEY_SLOT=1
+      echo "INFO: clearing LUKS key slot"
+      ;;
+    v)
+      DBG=1
+      echo "INFO: Debugging enabled"
+      ;;
+    h)
+      echo
+      echo " -d <partition>: set the partition"
+      echo " -s <slot>     : set the slot"
+      echo " -c            : clear the slot prior to writing"
+      echo " -v            : show input/output in cleartext"
+      echo
+      exit 1
+      ;;
+    \?)
+      printf '%s\n' "Invalid option: \"-$OPTARG\"" >&2
+      ;;
+  esac
+done
+
 if [ "$(id -u)" -ne 0 ]; then
   echo "Root required for this operation." 1>&2
   exit 1
 fi
 
-while getopts ":s:d:hcv" opt; do
-  case $opt in
-	s)
-		KEY_SLOT="$OPTARG"
-		printf '%s\n' "INFO: Setting LUKS key slot to \"$OPTARG\"."
-		;;
-	d)
-		YKFDE_LUKS_DEV="$OPTARG"
-		printf '%s\n' "INFO: Setting disk to \"$OPTARG\"."
-		;;
-	c)	CLEAR_KEY_SLOT=1
-		echo "INFO: clearing LUKS key slot"
-		;;
-	v)	DBG=1
-		echo "INFO: Debugging enabled"
-		;;
-	h)
-		echo 
-		echo " -d <partition>: set the partition"
-		echo " -s <slot>     : set the slot"
-		echo " -c            : clear the slot prior to writing"
-		echo " -v            : show input/output in cleartext"
-		echo
-		exit 1
-		;;
-	\?)
-		printf '%s\n' "Invalid option: \"-$OPTARG\"" >&2
-		;;
-  esac
-done
-
 if [ -z "$YKFDE_LUKS_DEV" ]; then
-    echo "Please select an existing partition using -d option, see ykfde-enroll -h for help."
-    exit 1
+  echo "Please select an existing partition using -d option, see ykfde-enroll -h for help."
+  exit 1
 fi
 
 if [ -z "$KEY_SLOT" ]; then
-    echo "Please select LUKS key slot using -s option, see ykfde-enroll -h for help."
-    exit 1
+  echo "Please select LUKS key slot using -s option, see ykfde-enroll -h for help."
+  exit 1
 fi
 
 if [ -n "$CLEAR_KEY_SLOT" ]; then
-	printf '%s\n' "Killing LUKS slot $KEY_SLOT"
-	cryptsetup luksKillSlot "$YKFDE_LUKS_DEV" "$KEY_SLOT"
+  printf '%s\n' "Killing LUKS slot $KEY_SLOT"
+  cryptsetup luksKillSlot "$YKFDE_LUKS_DEV" "$KEY_SLOT"
 fi
 
 printf '%s\n' "This script will utilize slot \"$KEY_SLOT\" on drive \"$YKFDE_LUKS_DEV\".  If this is not what you intended, please abort."
 
 if [ -n "$YKFDE_CHALLENGE_PASSWORD_NEEDED" ]; then
-    echo " > Please provide the challenge password."
-    while [ -z "$_pw" ]; do
-    printf "   Enter password: "; if [ "$DBG" ]; then read -r _pw; else read -r -s _pw; fi
+  echo " > Please provide the challenge password."
+  while [ -z "$_pw" ]; do
+    printf "   Enter password: "
+    if [ "$DBG" ]; then read -r _pw; else read -r -s _pw; fi
     printf "\\n > Please repeat the password.\\n"
-    printf "   Enter password: "; if [ "$DBG" ]; then read -r _pw2; else read -r -s _pw2; fi
+    printf "   Enter password: "
+    if [ "$DBG" ]; then read -r _pw2; else read -r -s _pw2; fi
     if [ "$_pw" != "$_pw2" ]; then
-	echo "Passwords do not match."
-	exit 1
+      echo "Passwords do not match."
+      exit 1
     fi
     _pw=$(printf %s "$_pw" | sha256sum | awk '{print $1}')
-    done
-    [ "$DBG" ] || echo # if /NOT/ DBG, we need to output \n here.
-    YKFDE_CHALLENGE="$_pw"
+  done
+  [ "$DBG" ] || echo # if /NOT/ DBG, we need to output \n here.
+  YKFDE_CHALLENGE="$_pw"
 fi
 
 [ "$DBG" ] && printf %s "   ykinfo -$YKFDE_CHALLENGE_SLOT \"$YKFDE_CHALLENGE\": "
-_tmp="$(ykinfo -"$YKFDE_CHALLENGE_SLOT" 2>&1)";
+_tmp="$(ykinfo -"$YKFDE_CHALLENGE_SLOT" 2>&1)"
 [ "$DBG" ] && printf '%s\n' "$_tmp"
 
 echo "   Remember to touch the device if necessary."
 [ "$DBG" ] && printf '%s\n' "   Running: ykchalresp -$YKFDE_CHALLENGE_SLOT \"$YKFDE_CHALLENGE\"..."
-_passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null| tr -d '\n')"
+_passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null | tr -d '\n')"
 
 if [ -z "$_passphrase" ]; then
-    echo "   YubiKey did not provide a response - Initializing second attempt, touch the device if necessary."
-    _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null| tr -d '\n')"
+  echo "   YubiKey did not provide a response - Initializing second attempt, touch the device if necessary."
+  _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null | tr -d '\n')"
 fi
 
 [ "$DBG" ] && printf '%s\n' "   Received response: '$_passphrase'"
 
 if [ -n "$_passphrase" ] && [ -n "$YKFDE_CHALLENGE_PASSWORD_NEEDED" ]; then
-    _passphrase="$_pw$_passphrase"
+  _passphrase="$_pw$_passphrase"
 fi
 
 [ "$DBG" ] && printf '%s\n' " > Using '$_passphrase' with cryptsetup!"
 echo "If prompted for a passphrase, enter the current passphrase for the LUKS container. This is the old LUKS passphrase."
-printf " Enter password: "; if [ "$DBG" ]; then read -r OLD; else read -r -s OLD; fi
+printf " Enter password: "
+if [ "$DBG" ]; then read -r OLD; else read -r -s OLD; fi
 
 if [ -n "$_passphrase" ]; then
-    [ "$DBG" ] && echo " > Adding new LUKS key (cryptsetup --key-slot=\"$KEY_SLOT\" luksAddKey \"$YKFDE_LUKS_DEV\")..." || printf "\\n > Decrypting (cryptsetup luksAddKey)...\\n"
-    printf '%s\n' "$OLD" "$_passphrase" "$_passphrase" | cryptsetup --key-slot="$KEY_SLOT" luksAddKey "$YKFDE_LUKS_DEV" 2>&1;
+  [ "$DBG" ] && echo " > Adding new LUKS key (cryptsetup --key-slot=\"$KEY_SLOT\" luksAddKey \"$YKFDE_LUKS_DEV\")..." || printf "\\n > Decrypting (cryptsetup luksAddKey)...\\n"
+  printf '%s\n' "$OLD" "$_passphrase" "$_passphrase" | cryptsetup --key-slot="$KEY_SLOT" luksAddKey "$YKFDE_LUKS_DEV" 2>&1
 else
-    echo "   Passphrase is empty. Operation aborted."
-    exit 1
+  echo "   Passphrase is empty. Operation aborted."
+  exit 1
 fi
 
 exit 0
diff --git a/src/ykfde-format b/src/ykfde-format
--- a/src/ykfde-format
+++ b/src/ykfde-format
@@ -6,46 +6,48 @@ set -e
 printf '%s\n' "This script will run 'cryptsetup luksFormat $*'.  If this is not what you intended, please abort."
 
 if [ -n "$YKFDE_CHALLENGE_PASSWORD_NEEDED" ]; then
-    echo " > Please provide the challenge password."
-    while [ -z "$_pw" ]; do
-    printf "   Enter password: "; if [ "$DBG" ]; then read -r _pw; else read -r -s _pw; fi
+  echo " > Please provide the challenge password."
+  while [ -z "$_pw" ]; do
+    printf "   Enter password: "
+    if [ "$DBG" ]; then read -r _pw; else read -r -s _pw; fi
     printf "\\n > Please repeat the password.\\n"
-    printf "   Enter password: "; if [ "$DBG" ]; then read -r _pw2; else read -r -s _pw2; fi
+    printf "   Enter password: "
+    if [ "$DBG" ]; then read -r _pw2; else read -r -s _pw2; fi
     if [ "$_pw" != "$_pw2" ]; then
-	echo "Passwords do not match."
-	exit 1
+      echo "Passwords do not match."
+      exit 1
     fi
     _pw=$(printf %s "$_pw" | sha256sum | awk '{print $1}')
-    done
-    [ "$DBG" ] || echo # if /NOT/ DBG, we need to output \n here.
-    YKFDE_CHALLENGE="$_pw"
+  done
+  [ "$DBG" ] || echo # if /NOT/ DBG, we need to output \n here.
+  YKFDE_CHALLENGE="$_pw"
 fi
 
 [ "$DBG" ] && printf %s "   ykinfo -$YKFDE_CHALLENGE_SLOT \"$YKFDE_CHALLENGE\": "
-_tmp="$(ykinfo -"$YKFDE_CHALLENGE_SLOT" 2>&1)";
+_tmp="$(ykinfo -"$YKFDE_CHALLENGE_SLOT" 2>&1)"
 [ "$DBG" ] && printf '%s\n' "$_tmp"
 
 echo "   Remember to touch the device if necessary."
 [ "$DBG" ] && printf '%s\n' "   Running: ykchalresp -$YKFDE_CHALLENGE_SLOT \"$YKFDE_CHALLENGE\"..."
-_passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null| tr -d '\n')"
+_passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null | tr -d '\n')"
 
 if [ -z "$_passphrase" ]; then
-    echo "   YubiKey did not provide a response - Initializing second attempt, touch the device if necessary."
-    _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null| tr -d '\n')"
+  echo "   YubiKey did not provide a response - Initializing second attempt, touch the device if necessary."
+  _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null | tr -d '\n')"
 fi
 
 [ "$DBG" ] && printf '%s\n' "   Received response: '$_passphrase'"
 
 if [ -n "$_passphrase" ] && [ -n "$YKFDE_CHALLENGE_PASSWORD_NEEDED" ]; then
-    _passphrase="$_pw$_passphrase"
+  _passphrase="$_pw$_passphrase"
 fi
 
 if [ -n "$_passphrase" ]; then
-    [ "$DBG" ] && printf '%s\n' " > Using '$_passphrase' with cryptsetup!"
-    printf '%s\n' "$_passphrase" | cryptsetup luksFormat "$@"
+  [ "$DBG" ] && printf '%s\n' " > Using '$_passphrase' with cryptsetup!"
+  printf '%s\n' "$_passphrase" | cryptsetup luksFormat "$@"
 else
-    echo "   Passphrase is empty. Operation aborted."
-    exit 1
+  echo "   Passphrase is empty. Operation aborted."
+  exit 1
 fi
 
 exit 0
diff --git a/src/ykfde-open b/src/ykfde-open
--- a/src/ykfde-open
+++ b/src/ykfde-open
@@ -3,92 +3,94 @@
 set -e
 . /etc/ykfde.conf
 
-mount=0
-
 while getopts ":d:n:hvpm" opt; do
   case $opt in
-	d)
-		YKFDE_LUKS_DEV="$OPTARG"
-		printf '%s\n' "INFO: Setting disk to \"$OPTARG\"."
-		;;
-	n)
-		YKFDE_LUKS_NAME="$OPTARG"
-		printf '%s\n' "INFO: Setting name to \"$OPTARG\"."
-		;;
-	v)	DBG=1
-		echo "INFO: Debugging enabled"
-		;;
-	p)	YKFDE_PRINT_ONLY=1
-		echo "INFO: Showing complied cleartext passphrase without unlocking"
-		;;
-	m)	mount=1
-		;;
-	h)
-		echo 
-		echo " -d <partition>: select an existing partition"
-		echo " -n <name>     : set the new container name"
-		echo " -v            : show input/output in cleartext"
-		echo " -p            : show cleartext passphrase without unlocking"
-		echo " -m            : mount unlocked device (non root user only)"
-		echo
-		exit 1
-		;;
-	\?)
-		printf '%s\n' "Invalid option: \"-$OPTARG\"" >&2
-		;;
+    d)
+      YKFDE_LUKS_DEV="$OPTARG"
+      printf '%s\n' "INFO: Setting disk to \"$OPTARG\"."
+      ;;
+    n)
+      YKFDE_LUKS_NAME="$OPTARG"
+      printf '%s\n' "INFO: Setting name to \"$OPTARG\"."
+      ;;
+    v)
+      DBG=1
+      echo "INFO: Debugging enabled"
+      ;;
+    p)
+      YKFDE_PRINT_ONLY=1
+      echo "INFO: Showing complied cleartext passphrase without unlocking"
+      ;;
+    m)
+      MOUNT=1
+      echo "INFO: Mounting device"
+      ;;
+    h)
+      echo
+      echo " -d <partition>: select an existing partition"
+      echo " -n <name>     : set the new container name"
+      echo " -v            : show input/output in cleartext"
+      echo " -p            : show cleartext passphrase without unlocking"
+      echo " -m            : mount unlocked device (non root user only)"
+      echo
+      exit 1
+      ;;
+    \?)
+      printf '%s\n' "Invalid option: \"-$OPTARG\"" >&2
+      ;;
   esac
 done
 
-if [ -z "$YKFDE_PRINT_ONLY" ] ; then
-	if [ -z "$YKFDE_LUKS_DEV" ]; then
-		echo "Please select an existing partition using -d option, see ykfde-open -h for help."
-		exit 1
-	fi
+if [ -z "$YKFDE_PRINT_ONLY" ]; then
+  if [ -z "$YKFDE_LUKS_DEV" ]; then
+    echo "Please select an existing partition using -d option, see ykfde-open -h for help."
+    exit 1
+  fi
 
-printf '%s\n' "This script will try to open the \"$YKFDE_LUKS_NAME\" LUKS container on drive \"$YKFDE_LUKS_DEV\" . If this is not what you intended, please abort."
+  printf '%s\n' "This script will try to open the \"$YKFDE_LUKS_NAME\" LUKS container on drive \"$YKFDE_LUKS_DEV\" . If this is not what you intended, please abort."
 
 fi
 
-
 if [ -n "$YKFDE_CHALLENGE_PASSWORD_NEEDED" ]; then
-    echo " > Please provide the challenge password."
-    while [ -z "$_pw" ]; do
-    printf "   Enter password: "; if [ "$DBG" ]; then read -r _pw; else read -r -s _pw; fi
+  echo " > Please provide the challenge password."
+  while [ -z "$_pw" ]; do
+    printf "   Enter password: "
+    if [ "$DBG" ]; then read -r _pw; else read -r -s _pw; fi
     _pw=$(printf %s "$_pw" | sha256sum | awk '{print $1}')
-    done
-    [ "$DBG" ] || echo # if /NOT/ DBG, we need to output \n here.
-    YKFDE_CHALLENGE="$_pw"
+  done
+  [ "$DBG" ] || echo # if /NOT/ DBG, we need to output \n here.
+  YKFDE_CHALLENGE="$_pw"
 fi
 
 [ "$DBG" ] && printf %s "   ykinfo -$YKFDE_CHALLENGE_SLOT \"$YKFDE_CHALLENGE\": "
-_tmp="$(ykinfo -"$YKFDE_CHALLENGE_SLOT" 2>&1)";
+_tmp="$(ykinfo -"$YKFDE_CHALLENGE_SLOT" 2>&1)"
 [ "$DBG" ] && printf '%s\n' "$_tmp"
 
 echo "   Remember to touch the device if necessary."
 [ "$DBG" ] && printf '%s\n' "   Running: ykchalresp -$YKFDE_CHALLENGE_SLOT \"$YKFDE_CHALLENGE\"..."
-_passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null| tr -d '\n')"
+_passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null | tr -d '\n')"
 
 if [ -z "$_passphrase" ]; then
-    echo "   YubiKey did not provide a response - Initializing second attempt, touch the device if necessary."
-    _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null| tr -d '\n')"
+  echo "   YubiKey did not provide a response - Initializing second attempt, touch the device if necessary."
+  _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null | tr -d '\n')"
 fi
 
 [ "$DBG" ] && printf '%s\n' "   Received response: '$_passphrase'"
 
 if [ -n "$_passphrase" ] && [ -n "$YKFDE_CHALLENGE_PASSWORD_NEEDED" ]; then
-    _passphrase="$_pw$_passphrase"
+  _passphrase="$_pw$_passphrase"
 fi
 
-if [ -n "$YKFDE_PRINT_ONLY" ] ; then
-	printf '%s\n' " > Passphrase: $_passphrase"
-	exit 0
+if [ -n "$YKFDE_PRINT_ONLY" ]; then
+  printf '%s\n' " > Passphrase: $_passphrase"
+  exit 0
 fi
 
 [ "$DBG" ] && printf '%s\n' " > Passing '$_passphrase' to cryptsetup!"
 [ "$DBG" ] && printf '%s\n' " > Decrypting (cryptsetup luksOpen \"$YKFDE_LUKS_DEV\" \"$YKFDE_LUKS_NAME\")..." || echo " > Decrypting (cryptsetup luksOpen)..."
 
 if [ "$(id -u)" -eq 0 ]; then
-  printf %s "$_passphrase"| cryptsetup luksOpen "$YKFDE_LUKS_DEV" "$YKFDE_LUKS_NAME" 2>&1;
+  printf %s "$_passphrase" | cryptsetup luksOpen "$YKFDE_LUKS_DEV" "$YKFDE_LUKS_NAME" 2>&1
 else
   expect <(cat <<EXPECTSCRIPT
 	set timeout -1
@@ -98,7 +100,7 @@ else
 	send -- "${_passphrase}\\r"
 	expect -re "Unlocked .* as (.*).\\r\\n" {
 		set unlocked \$expect_out(1,string)
-		if ($mount) {
+		if ("$MOUNT") {
 			spawn udisksctl mount -b \$unlocked
 			expect eof
 		}
