ykfde hook: sort functions chronologically as they are called
This should improve code readability. No functional changes.

diff --git a/src/hooks/ykfde b/src/hooks/ykfde
--- a/src/hooks/ykfde
+++ b/src/hooks/ykfde
@@ -5,12 +5,124 @@ YKFDE_CONFIG_FILE="/etc/ykfde.conf"
 DEFAULT_CRYPTSETUP_TRIALS=5                 # defaults number of times to try 'do_it()' -- so: assemble passphrase and run 'cryptsetup luksOpen'
 DEFAULT_CHALLENGE_YUBIKEY_INSERT_TIMEOUT=30 # default value for YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT. -1 = unlimited
 
+run_hook() {
+  local _tmp=""
+  local cryptargs cryptopt cryptoptions
+
+  [ "$DBG" ] && echo "$0:"
+
+  [ "$DBG" ] && echo " > Reading YKFDE configuration file."
+  . "$YKFDE_CONFIG_FILE" || {
+    ykfde_err 001 "Failed to read the YKFDE configuration file '$YKFDE_CONFIG_FILE'"
+    return 1
+  }
+
+  # no settings in config, try to pull it from kernel cmdline (analog to encrypt hook)
+  if [ -z "$YKFDE_DISK_UUID" ] || [ -z "$YKFDE_LUKS_NAME" ]; then
+    if [ "$cryptdevice" ]; then
+      IFS=: read -r YKFDE_LUKS_DEV YKFDE_LUKS_NAME cryptoptions <<EOF
+$cryptdevice
+EOF
+      for cryptopt in $(echo "$cryptoptions" | tr , ' '); do
+        case "$cryptopt" in
+          allow-discards)
+            cryptargs="$cryptargs --allow-discards"
+            ;;
+          *)
+            ykfde_err 001 "Encryption option '$cryptopt' not known, ignoring."
+            ;;
+        esac
+      done
+      YKFDE_LUKS_OPTIONS="$cryptargs"
+      YKFDE_LUKS_DEV="$(resolve_device "$YKFDE_LUKS_DEV")"
+    else
+      ykfde_err 002 "'$YKFDE_CONFIG_FILE' Please provide YKFDE_DISK_UUID /and/ YKFDE_LUKS_NAME or set cryptdevice kernel parameter."
+      return 1
+    fi
+  fi
+
+  # set default values:
+  [ -z "$YKFDE_LUKS_DEV" ] && YKFDE_LUKS_DEV="/dev/disk/by-uuid/$YKFDE_DISK_UUID"
+  [ -z "$YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT" ] && YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT="$DEFAULT_CHALLENGE_YUBIKEY_INSERT_TIMEOUT"
+  [ -z "$YKFDE_CRYPTSETUP_TRIALS" ] && YKFDE_CRYPTSETUP_TRIALS="$DEFAULT_CRYPTSETUP_TRIALS"
+
+  # sanity checks:
+  [ "$YKFDE_CRYPTSETUP_TRIALS" -gt 0 ] || {
+    ykfde_err 004 "YKFDE_CRYPTSETUP_TRIALS needs to be higher than 0."
+    return 1
+  }
+
+  [ "$DBG" ] && echo " > modprobing dm-crypt"
+  _tmp="$(modprobe -a -q dm-crypt >/dev/null 2>&1)"
+
+  local trial_nr=1
+  while [ "$trial_nr" -le "$YKFDE_CRYPTSETUP_TRIALS" ]; do
+    printf '%s\n' "Attempt #$trial_nr/$YKFDE_CRYPTSETUP_TRIALS: cryptsetup of $YKFDE_LUKS_DEV"
+    ykfde_do_it && return 0
+    trial_nr=$((trial_nr + 1))
+  done
+
+  # if we get here, we did NOT succeed:
+  ykfde_err 000 "$0 Failed!"
+  return 1
+}
+
 ykfde_err() {
   local rc="$?"
   local code="$1"
   local msg="$2"
   [ "$msg" ] && msg="ERROR $code [rc=$rc]: $msg" || msg="ERROR $code [rc=$rc]"
   printf '\n%s\n\n' "$msg" #exit 1;
+}
+
+# assemble passphrase and run 'cryptsetup luksOpen'
+ykfde_do_it() {
+  local _passphrase="" # key used to 'cryptsetup luksOpen'
+  local _tmp=""
+  local _rc=""
+
+  # if we have a challenge
+  [ "$YKFDE_CHALLENGE" ] && ykfde_challenge_response
+
+  if [ -z "$_passphrase" ]; then
+    if [ "$YKFDE_CHALLENGE" ]; then
+      printf " > Challenge-response failed.\\n   Falling back to manual passphrase.\\n"
+      [ "$trial_nr" -le "$YKFDE_CRYPTSETUP_TRIALS" ] && echo "   Press ENTER to skip and retry Challenge-Response."
+    else
+      echo " > Passphrase needed to unlock disk."
+    fi
+
+    printf "   Enter passphrase: "
+    if [ "$DBG" ]; then read -r _passphrase; else read -r -s _passphrase; fi
+    [ "$DBG" ] || echo # if /NOT/ DBG, we need to output \n here.
+  fi
+
+  [ -e "$YKFDE_LUKS_DEV" ] || {
+    ykfde_err 003 "YKFDE cannot find LUKS device '$YKFDE_LUKS_DEV'.\\nPlease check YKFDE_DISK_UUID ($YKFDE_DISK_UUID) and/or YKFDE_LUKS_DEV variable(s) in '$YKFDE_CONFIG_FILE'."
+    return 1
+  }
+
+  [ "$DBG" ] && echo " > Passing '$_passphrase' to cryptsetup!"
+  if [ "$RESUME" ]; then
+    [ "$DBG" ] && echo " > Decrypting (cryptsetup luksResume \"$cryptname\"..." || echo " > Decrypting (cryptsetup luksResume)..."
+    _tmp="$(printf %s "$_passphrase" | cryptsetup luksResume "$cryptname" 2>&1)"
+  else
+    [ "$DBG" ] && echo " > Decrypting (cryptsetup luksOpen \"$YKFDE_LUKS_DEV\" \"$YKFDE_LUKS_NAME\")..." || echo " > Decrypting (cryptsetup luksOpen)..."
+    _tmp="$(printf %s "$_passphrase" | cryptsetup luksOpen "$YKFDE_LUKS_DEV" "$YKFDE_LUKS_NAME" "$YKFDE_LUKS_OPTIONS" 2>&1)"
+  fi
+  _rc=$?
+
+  if [ "$_rc" -eq 0 ]; then
+    echo "   Decryption was succesful."
+    if [ "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP" ] && [ "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP" -gt 0 ]; then
+      [ "$DBG" ] && echo " > Making $YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP sleep."
+      sleep "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP"
+    fi
+  else
+    echo "   FAILED! [$_rc] $_tmp"
+  fi
+
+  return "$_rc"
 }
 
 ykfde_challenge_response() {
@@ -72,116 +184,4 @@ ykfde_challenge_response() {
   if [ "$_passphrase" ] && [ "$YKFDE_CHALLENGE_PASSWORD_NEEDED" ]; then
     _passphrase="$_pw$_passphrase"
   fi
-}
-
-# assemble passphrase and run 'cryptsetup luksOpen'
-ykfde_do_it() {
-  local _passphrase="" # key used to 'cryptsetup luksOpen'
-  local _tmp=""
-  local _rc=""
-
-  # if we have a challenge
-  [ "$YKFDE_CHALLENGE" ] && ykfde_challenge_response
-
-  if [ -z "$_passphrase" ]; then
-    if [ "$YKFDE_CHALLENGE" ]; then
-      printf " > Challenge-response failed.\\n   Falling back to manual passphrase.\\n"
-      [ "$trial_nr" -le "$YKFDE_CRYPTSETUP_TRIALS" ] && echo "   Press ENTER to skip and retry Challenge-Response."
-    else
-      echo " > Passphrase needed to unlock disk."
-    fi
-
-    printf "   Enter passphrase: "
-    if [ "$DBG" ]; then read -r _passphrase; else read -r -s _passphrase; fi
-    [ "$DBG" ] || echo # if /NOT/ DBG, we need to output \n here.
-  fi
-
-  [ -e "$YKFDE_LUKS_DEV" ] || {
-    ykfde_err 003 "YKFDE cannot find LUKS device '$YKFDE_LUKS_DEV'.\\nPlease check YKFDE_DISK_UUID ($YKFDE_DISK_UUID) and/or YKFDE_LUKS_DEV variable(s) in '$YKFDE_CONFIG_FILE'."
-    return 1
-  }
-
-  [ "$DBG" ] && echo " > Passing '$_passphrase' to cryptsetup!"
-  if [ "$RESUME" ]; then
-    [ "$DBG" ] && echo " > Decrypting (cryptsetup luksResume \"$cryptname\"..." || echo " > Decrypting (cryptsetup luksResume)..."
-    _tmp="$(printf %s "$_passphrase" | cryptsetup luksResume "$cryptname" 2>&1)"
-  else
-    [ "$DBG" ] && echo " > Decrypting (cryptsetup luksOpen \"$YKFDE_LUKS_DEV\" \"$YKFDE_LUKS_NAME\")..." || echo " > Decrypting (cryptsetup luksOpen)..."
-    _tmp="$(printf %s "$_passphrase" | cryptsetup luksOpen "$YKFDE_LUKS_DEV" "$YKFDE_LUKS_NAME" "$YKFDE_LUKS_OPTIONS" 2>&1)"
-  fi
-  _rc=$?
-
-  if [ "$_rc" -eq 0 ]; then
-    echo "   Decryption was succesful."
-    if [ "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP" ] && [ "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP" -gt 0 ]; then
-      [ "$DBG" ] && echo " > Making $YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP sleep."
-      sleep "$YKFDE_SLEEP_AFTER_SUCCESSFUL_CRYPTSETUP"
-    fi
-  else
-    echo "   FAILED! [$_rc] $_tmp"
-  fi
-
-  return "$_rc"
-}
-
-run_hook() {
-  local _tmp=""
-  local cryptargs cryptopt cryptoptions
-
-  [ "$DBG" ] && echo "$0:"
-
-  [ "$DBG" ] && echo " > Reading YKFDE configuration file."
-  . "$YKFDE_CONFIG_FILE" || {
-    ykfde_err 001 "Failed to read the YKFDE configuration file '$YKFDE_CONFIG_FILE'"
-    return 1
-  }
-
-  # no settings in config, try to pull it from kernel cmdline (analog to encrypt hook)
-  if [ -z "$YKFDE_DISK_UUID" ] || [ -z "$YKFDE_LUKS_NAME" ]; then
-    if [ "$cryptdevice" ]; then
-      IFS=: read -r YKFDE_LUKS_DEV YKFDE_LUKS_NAME cryptoptions <<EOF
-$cryptdevice
-EOF
-      for cryptopt in $(echo "$cryptoptions" | tr , ' '); do
-        case "$cryptopt" in
-          allow-discards)
-            cryptargs="$cryptargs --allow-discards"
-            ;;
-          *)
-            ykfde_err 001 "Encryption option '$cryptopt' not known, ignoring."
-            ;;
-        esac
-      done
-      YKFDE_LUKS_OPTIONS="$cryptargs"
-      YKFDE_LUKS_DEV="$(resolve_device "$YKFDE_LUKS_DEV")"
-    else
-      ykfde_err 002 "'$YKFDE_CONFIG_FILE' Please provide YKFDE_DISK_UUID /and/ YKFDE_LUKS_NAME or set cryptdevice kernel parameter."
-      return 1
-    fi
-  fi
-
-  # set default values:
-  [ -z "$YKFDE_LUKS_DEV" ] && YKFDE_LUKS_DEV="/dev/disk/by-uuid/$YKFDE_DISK_UUID"
-  [ -z "$YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT" ] && YKFDE_CHALLENGE_YUBIKEY_INSERT_TIMEOUT="$DEFAULT_CHALLENGE_YUBIKEY_INSERT_TIMEOUT"
-  [ -z "$YKFDE_CRYPTSETUP_TRIALS" ] && YKFDE_CRYPTSETUP_TRIALS="$DEFAULT_CRYPTSETUP_TRIALS"
-
-  # sanity checks:
-  [ "$YKFDE_CRYPTSETUP_TRIALS" -gt 0 ] || {
-    ykfde_err 004 "YKFDE_CRYPTSETUP_TRIALS needs to be higher than 0."
-    return 1
-  }
-
-  [ "$DBG" ] && echo " > modprobing dm-crypt"
-  _tmp="$(modprobe -a -q dm-crypt >/dev/null 2>&1)"
-
-  local trial_nr=1
-  while [ "$trial_nr" -le "$YKFDE_CRYPTSETUP_TRIALS" ]; do
-    printf '%s\n' "Attempt #$trial_nr/$YKFDE_CRYPTSETUP_TRIALS: cryptsetup of $YKFDE_LUKS_DEV"
-    ykfde_do_it && return 0
-    trial_nr=$((trial_nr + 1))
-  done
-
-  # if we get here, we did NOT succeed:
-  ykfde_err 000 "$0 Failed!"
-  return 1
 }
