Grammar fixes

diff --git a/src/ykfde-enroll b/src/ykfde-enroll
--- a/src/ykfde-enroll
+++ b/src/ykfde-enroll
@@ -5,7 +5,7 @@ set -e
 . /etc/ykfde.conf
 
 if [ "$(id -u)" -ne 0 ]; then
-  echo "You must be root." 1>&2
+  echo "Root required for this operation." 1>&2
   exit 1
 fi
 
@@ -41,7 +41,7 @@ while getopts ":s:d:hcv" opt; do
 done
 
 if [ -z "$YKFDE_LUKS_DEV" ]; then
-    echo "Please select existing partition using -d option, see ykfde-enroll -h for help."
+    echo "Please select an existing partition using -d option, see ykfde-enroll -h for help."
     exit 1
 fi
 
@@ -55,16 +55,16 @@ if [ $CLEAR_KEY_SLOT -eq 1 ]; then
 	cryptsetup luksKillSlot "$YKFDE_LUKS_DEV" "$KEY_SLOT"
 fi
 
-echo "This script will utilize slot $KEY_SLOT on drive $YKFDE_LUKS_DEV.  If this is not what you intended, exit now!"
+echo "This script will utilize slot $KEY_SLOT on drive $YKFDE_LUKS_DEV.  If this is not what you intended, please abort."
 
 if [ "$YKFDE_CHALLENGE_PASSWORD_NEEDED" = "1" ]; then
-    echo " > Please provide password which will be used as challenge."
+    echo " > Please provide the challenge password."
     while [ -z "$_pw" ]; do
     printf "   Enter password: "; if [ "$DBG" ]; then read -r _pw; else read -r -s _pw; fi
-    echo " > Please provide the same password again."
+    echo " > Please repeat the password."
     printf "   Enter password: "; if [ "$DBG" ]; then read -r _pw2; else read -r -s _pw2; fi
     if [ "$_pw" != "$_pw2" ]; then
-	echo "Passwords do not match"
+	echo "Passwords do not match."
 	exit 1
     fi
     _pw=$(printf %s "$_pw" | sha256sum | awk '{print $1}')
@@ -77,24 +77,23 @@ fi
 _tmp="$(ykinfo -"$YKFDE_CHALLENGE_SLOT" 2>&1)";
 [ "$DBG" ] && echo "$_tmp"
 
-echo "   Don't forget to press its button if necessary..."
-[ "$DBG" ] && echo "   Running NOW: ykchalresp -$YKFDE_CHALLENGE_SLOT \"$YKFDE_CHALLENGE\"..."
+echo "   Remember to touch the device if necessary."
+[ "$DBG" ] && echo "   Running: ykchalresp -$YKFDE_CHALLENGE_SLOT \"$YKFDE_CHALLENGE\"..."
 _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null| tr -d '\n')"
 
 if [ -z "$_passphrase" ]; then
-    printf "\n   NO response from YubiKey!? - We try again! (so press the button now?!)...\n"
+    printf "\n   Yubikey did not provide a response - Lets try again!\n"
     _passphrase="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_CHALLENGE" 2>/dev/null| tr -d '\n')"
 fi
 
-[ "$DBG" ] && printf "\n   Got as response: '$_passphrase'\n"
+[ "$DBG" ] && printf "\n   Received response: '$_passphrase'\n"
 
 if [ -n "$_passphrase" ] && [ "$YKFDE_CHALLENGE_PASSWORD_NEEDED" = "1" ]; then
     _passphrase="$_pw$_passphrase"
 fi
 
 [ "$DBG" ] && echo " > Using '$_passphrase' with cryptsetup!"
-echo "You may now be prompted for an existing passphrase. This is NOT the passphrase you just entered, this is the passphrase that you currently use to unlock your LUKS encrypted drive."
-printf "   Enter password: "; if [ "$DBG" ]; then read -r OLD; else read -r -s OLD; fi
+echo "If prompted for a passphrase, enter the old registered passphrase for your LUKS container."
 [ "$DBG" ] && echo " > Adding new LUKS key (cryptsetup --key-slot=\"$KEY_SLOT\" luksAddKey \"$YKFDE_LUKS_DEV\")..." || echo " > Decrypting (cryptsetup luksAddKey)..."
 printf '%s\n' "$OLD" "$_passphrase" "$_passphrase" | cryptsetup --key-slot="$KEY_SLOT" luksAddKey "$YKFDE_LUKS_DEV" 2>&1;
 
