Abort operation if Luks passphrase is empty

diff --git a/src/ykfde-enroll b/src/ykfde-enroll
--- a/src/ykfde-enroll
+++ b/src/ykfde-enroll
@@ -94,7 +94,13 @@ fi
 [ "$DBG" ] && printf '%s\n' " > Using '$_passphrase' with cryptsetup!"
 echo "If prompted for a passphrase, enter the current passphrase for the LUKS container. This is the old LUKS passphrase."
 printf " Enter password: "; if [ "$DBG" ]; then read -r OLD; else read -r -s OLD; fi
-[ "$DBG" ] && echo " > Adding new LUKS key (cryptsetup --key-slot=\"$KEY_SLOT\" luksAddKey \"$YKFDE_LUKS_DEV\")..." || printf "\\n > Decrypting (cryptsetup luksAddKey)...\\n"
-printf '%s\n' "$OLD" "$_passphrase" "$_passphrase" | cryptsetup --key-slot="$KEY_SLOT" luksAddKey "$YKFDE_LUKS_DEV" 2>&1;
+
+if [ -n "$_passphrase" ]; then
+    [ "$DBG" ] && echo " > Adding new LUKS key (cryptsetup --key-slot=\"$KEY_SLOT\" luksAddKey \"$YKFDE_LUKS_DEV\")..." || printf "\\n > Decrypting (cryptsetup luksAddKey)...\\n"
+    printf '%s\n' "$OLD" "$_passphrase" "$_passphrase" | cryptsetup --key-slot="$KEY_SLOT" luksAddKey "$YKFDE_LUKS_DEV" 2>&1;
+else
+    echo "   Passphrase is empty. Operation aborted."
+    exit 1
+fi
 
 exit 0
