Add support to disenroll existing key slot with YubiKey

diff --git a/src/ykfde-enroll b/src/ykfde-enroll
--- a/src/ykfde-enroll
+++ b/src/ykfde-enroll
@@ -9,12 +9,15 @@ CHANGE_KEYSLOT=""
 OLD_YUBIKEY=""
 DBG=""
 YKFDE_SLOT_CHECK=""
+YKFDE_SLOT_KILL=""
 YKFDE_CHALLENGE_SLOT="2"
 YKFDE_CHALLENGE_PASSWORD_NEEDED=""
 YKFDE_CHALLENGE=""
-YKFDE_OLD_CHALLENGE=""
 YKFDE_RESPONSE=""
 YKFDE_PASSPHRASE=""
+YKFDE_OLD_CHALLENGE=""
+YKFDE_OLD_RESPONSE=""
+YKFDE_OLD_PASSPHRASE=""
 
 if [ -r /etc/ykfde.conf ]; then
   # shellcheck source=ykfde.conf
@@ -23,7 +26,7 @@ else
   echo "WARNING: Can't access /etc/ykfde.conf. Falling back to defaults."
 fi
 
-while getopts ":d:s:ocvh" opt; do
+while getopts ":d:s:ckovh" opt; do
   case "$opt" in
     d)
       YKFDE_LUKS_DEV="$OPTARG"
@@ -42,6 +45,10 @@ while getopts ":d:s:ocvh" opt; do
       CHANGE_KEYSLOT=1
       echo "INFO: Changing existing LUKS keyslot"
       ;;
+    k)
+      YKFDE_SLOT_KILL=1
+      echo "WARNING: Killing existing LUKS keyslot. If it's the last configured keyslot, the device will be inaccessible!"
+      ;;
     o)
       OLD_YUBIKEY=1
       echo "INFO: Using old YubiKey for passphrase"
@@ -55,6 +62,7 @@ while getopts ":d:s:ocvh" opt; do
       echo " -d <device>   : select an existing device"
       echo " -s <slot>     : select the LUKS keyslot"
       echo " -c            : change an existing keyslot"
+      echo " -k            : killing an existing keyslot"
       echo " -o            : use old YubiKey for passphrase"
       echo " -v            : show input/output in cleartext"
       echo
@@ -66,6 +74,7 @@ while getopts ":d:s:ocvh" opt; do
       echo " -d <device>   : select an existing device"
       echo " -s <slot>     : select the LUKS keyslot"
       echo " -c            : change an existing keyslot"
+      echo " -k            : killing an existing keyslot"
       echo " -o            : use old YubiKey for passphrase"
       echo " -v            : show input/output in cleartext"
       echo
@@ -111,6 +120,7 @@ printf '%s\n' "WARNING: This script will utilize LUKS keyslot '$LUKS_KEYSLOT' on
 
 [ -z "$YKFDE_CHALLENGE" ] && YKFDE_CHALLENGE_PASSWORD_NEEDED=1
 [ "$YKFDE_CHALLENGE_PASSWORD_NEEDED" ] && YKFDE_CHALLENGE=""
+
 while [ -z "$YKFDE_CHALLENGE" ]; do
   echo " > Please provide the challenge."
   printf "   Enter challenge: "
@@ -154,59 +164,63 @@ if [ "$YKFDE_RESPONSE" ]; then
   fi
 fi
 
-if [ $OLD_YUBIKEY=1 ]
-then
-    echo "Please remove new YubiKey and insert old YubiKey for existing keyslot."
+if [ "$YKFDE_SLOT_KILL" ]; then
+  [ "$DBG" ] && printf '%s\n' " > Killing with 'cryptsetup luksKillSlot $YKFDE_LUKS_DEV $LUKS_KEYSLOT'..." || echo " > Killing slot with 'cryptsetup'..."
+  printf %s "$YKFDE_PASSPHRASE" | cryptsetup luksKillSlot "$YKFDE_LUKS_DEV" "$LUKS_KEYSLOT" 2>&1
+  printf '%s\n' "   LUKS key slot $LUKS_KEYSLOT successfully killed"
+  exit 0
+fi
 
-    while [ -z "$YKFDE_OLD_CHALLENGE" ]; do
-      echo " > Please provide the old challenge."
-      printf "   Enter challenge: "
-      if [ "$DBG" ]; then read -r YKFDE_OLD_CHALLENGE; else read -r -s YKFDE_OLD_CHALLENGE; fi
-      printf "\\n > Please repeat the old challenge.\\n"
-      printf "   Enter challenge: "
-      if [ "$DBG" ]; then read -r YKFDE_OLD_CHALLENGE2; else read -r -s YKFDE_OLD_CHALLENGE2; fi
-      if [ "$YKFDE_OLD_CHALLENGE" != "$YKFDE_OLD_CHALLENGE2" ]; then
-        echo "WARNING: Challenges do not match. Try again."
-        YKFDE_OLD_CHALLENGE=""
-      fi
-      [ "$YKFDE_OLD_CHALLENGE" ] && YKFDE_OLD_CHALLENGE="$(printf %s "$YKFDE_OLD_CHALLENGE" | sha256sum | awk '{print $1}')"
-      # if /NOT/ DBG, we need to output \n here.
-      [ "$DBG" ] || echo
-    done
+if [ "$OLD_YUBIKEY" ]; then
+  echo "Please insert old YubiKey for existing keyslot."
 
-    if [ -z "$YKFDE_OLD_CHALLENGE" ]; then
-      echo "ERROR: ykfde old challenge is empty. Operation aborted."
-      exit 1
+  while [ -z "$YKFDE_OLD_CHALLENGE" ]; do
+    echo " > Please provide the old challenge."
+    printf "   Enter challenge: "
+    if [ "$DBG" ]; then read -r YKFDE_OLD_CHALLENGE; else read -r -s YKFDE_OLD_CHALLENGE; fi
+    printf "\\n > Please repeat the old challenge.\\n"
+    printf "   Enter challenge: "
+    if [ "$DBG" ]; then read -r YKFDE_OLD_CHALLENGE2; else read -r -s YKFDE_OLD_CHALLENGE2; fi
+    if [ "$YKFDE_OLD_CHALLENGE" != "$YKFDE_OLD_CHALLENGE2" ]; then
+      echo "WARNING: Challenges do not match. Try again."
+      YKFDE_OLD_CHALLENGE=""
     fi
+    [ "$YKFDE_OLD_CHALLENGE" ] && YKFDE_OLD_CHALLENGE="$(printf %s "$YKFDE_OLD_CHALLENGE" | sha256sum | awk '{print $1}')"
+    # if /NOT/ DBG, we need to output \n here.
+    [ "$DBG" ] || echo
+  done
 
-    echo "   Remember to touch the old device if necessary."
+  if [ -z "$YKFDE_OLD_CHALLENGE" ]; then
+    echo "ERROR: ykfde old challenge is empty. Operation aborted."
+    exit 1
+  fi
 
-    if [ "$DBG" ]; then read -r YKFDE_OLD_PASSPHRASE; else read -r -s YKFDE_OLD_PASSPHRASE; fi
+  echo "   Remember to touch the old device if necessary."
 
-    [ "$DBG" ] && printf '%s\n' "   Running: 'ykchalresp -$YKFDE_CHALLENGE_SLOT $YKFDE_OLD_CHALLENGE'..."
-    # we have to temporary disable '-e' shell option otherwise there would bo no chance for second attempt
-    set +e
-    YKFDE_OLD_RESPONSE="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_OLD_CHALLENGE" 2>/dev/null | tr -d '\n')"
-    set -e
-    if [ -z "$YKFDE_OLD_RESPONSE" ]; then
-      sleep 3
-      echo "   YubiKey did not provide a response - Initializing second attempt, touch the device if necessary."
-      YKFDE_OLD_RESPONSE="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_OLD_CHALLENGE" | tr -d '\n')"
+  [ "$DBG" ] && printf '%s\n' "   Running: 'ykchalresp -$YKFDE_CHALLENGE_SLOT $YKFDE_OLD_CHALLENGE'..."
+  # we have to temporary disable '-e' shell option otherwise there would bo no chance for second attempt
+  set +e
+  YKFDE_OLD_RESPONSE="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_OLD_CHALLENGE" 2>/dev/null | tr -d '\n')"
+  set -e
+  if [ -z "$YKFDE_OLD_RESPONSE" ]; then
+    sleep 3
+    echo "   YubiKey did not provide a response - Initializing second attempt, touch the device if necessary."
+    YKFDE_OLD_RESPONSE="$(ykchalresp -"$YKFDE_CHALLENGE_SLOT" "$YKFDE_OLD_CHALLENGE" | tr -d '\n')"
+  fi
+
+  [ "$DBG" ] && printf '%s\n' "   Received response: '$YKFDE_OLD_RESPONSE'"
+
+  if [ "$YKFDE_OLD_RESPONSE" ]; then
+    if [ "$YKFDE_CHALLENGE_PASSWORD_NEEDED" ]; then
+      YKFDE_OLD_PASSPHRASE="$YKFDE_OLD_CHALLENGE$YKFDE_OLD_RESPONSE"
+    else
+      YKFDE_OLD_PASSPHRASE="$YKFDE_OLD_RESPONSE"
     fi
-
-    [ "$DBG" ] && printf '%s\n' "   Received response: '$YKFDE_OLD_RESPONSE'"
-
-    if [ "$YKFDE_OLD_RESPONSE" ]; then
-      if [ "$YKFDE_CHALLENGE_PASSWORD_NEEDED" ]; then
-        YKFDE_OLD_PASSPHRASE="$YKFDE_OLD_CHALLENGE$YKFDE_OLD_RESPONSE"
-      else
-        YKFDE_OLD_PASSPHRASE="$YKFDE_RESPONSE"
-      fi
-    fi
+  fi
 else
-    echo "Please provide the old LUKS passphrase for the existing keyslot."
-    printf " Enter passphrase: "
-    if [ "$DBG" ]; then read -r YKFDE_OLD_PASSPHRASE; else read -r -s YKFDE_OLD_PASSPHRASE; fi
+  echo "Please provide the old LUKS passphrase for the existing keyslot."
+  printf " Enter passphrase: "
+  if [ "$DBG" ]; then read -r YKFDE_OLD_PASSPHRASE; else read -r -s YKFDE_OLD_PASSPHRASE; fi
 fi
 
 if [ "$YKFDE_PASSPHRASE" ]; then
@@ -214,15 +228,15 @@ if [ "$YKFDE_PASSPHRASE" ]; then
   if [ "$CHANGE_KEYSLOT" ]; then
     [ "$DBG" ] && printf '%s\n' " > Changing LUKS passphrase with 'cryptsetup --key-slot=$LUKS_KEYSLOT luksChangeKey $YKFDE_LUKS_DEV'..." || echo " > Changing LUKS passphrase with 'cryptsetup'..."
     printf '%s\n' "$YKFDE_OLD_PASSPHRASE" "$YKFDE_PASSPHRASE" "$YKFDE_PASSPHRASE" | cryptsetup --key-slot="$LUKS_KEYSLOT" luksChangeKey "$YKFDE_LUKS_DEV" 2>&1
+    printf '%s\n' "   LUKS passphrase for key slot $LUKS_KEYSLOT successfully changed"
   else
     [ "$DBG" ] && printf '%s\n' " > Adding new LUKS passphrase with 'cryptsetup --key-slot=$LUKS_KEYSLOT luksAddKey $YKFDE_LUKS_DEV'..." || echo " > Adding new LUKS passphrase with 'cryptsetup'..."
     printf '%s\n' "$YKFDE_OLD_PASSPHRASE" "$YKFDE_PASSPHRASE" "$YKFDE_PASSPHRASE" | cryptsetup --key-slot="$LUKS_KEYSLOT" luksAddKey "$YKFDE_LUKS_DEV" 2>&1
+    printf '%s\n' "   New LUKS passphrase successfully added"
   fi
 else
   echo "ERROR: ykfde passphrase is empty. Operation aborted."
   exit 1
 fi
-
-echo "   New LUKS passphrase successfully added"
 
 exit 0
